import { RFValue } from "react-native-responsive-fontsize";

export default {
  COLORS:{
    ALERT: "#ec1414",

    ICON: '#1e1e1e', //COR DOS CADEADOS E DAS SETAS PARA O LADO

    BACKGROUND_HEADER: "none", //COR DE TODOS OS CABEÇALHOS
    ICON_HEADER: "#2e2e2e", //COR DA PALAVRA LOGIN, ACESSAR APLICATIVO E DRAWER NO HEADER (MAIN E ABOUT)

    //TELA ABOUT - INSTITUCIONAL
    BACKGROUND_ABOUT: "white", //COR PARA A ABOUT, DRAWER, CLICK COURSE, PLANS, EDITPROFILE, LOGIN E CADASTRO
    TITLE_OVERPHOTO_ABOUT: "white", //USADA PARA O TÍTULO DA ABOUT
    SUBTITLE_OVERPHOTO_ABOUT: "white", //USADA PARA O SUBTÍTULO DA ABOUT
    TITLE_ABOUT: '#2e2e2e', //USADA PARA PARA OS TAMANHOS EXTRABIG, BIG E STANDARD
    TEXT_ABOUT: '#2e2e2e', //USADA PARA PARA OS TAMANHOS MEDIUM, SMALL E EXTRASMALL

    //TELA MAIN
    BACKGROUND_MAIN: "#2e2e2e", //COR PARA A MAIN E CLICKCLASS
    TITLE_OVERPHOTO_MAIN: "white", //USADA PARA O TÍTULO E SUBTÍTULO DA MAIN
    TITLE_MAIN: 'white', //USADA PARA PARA OS TAMANHOS EXTRABIG, BIG E STANDARD
    TEXT_MAIN: 'white', //USADA PARA PARA OS TAMANHOS MEDIUM, SMALL E EXTRASMALL

    //FOOTER TELA ABOUT E DRAWER
    BACKGROUND_FOOTER: "#2e2e2e", //COR DO RODAPÉ
    TEXT_FOOTER: 'white', //USADA PARA O TEXTO DO RODAPÉ

    //BOTÕES PRINCIPAIS - COR DE FUNDO É A PRIMARY_900
    TEXT_BUTTON: "white", //USADA PARA O TEXTO DOS BOTÕES
 
    //CORES GERAIS
    PRIMARY_900: "#8EB87D", //COR PRINCIPAL DO APP - CORES DOS BOTÕES, LATERAL DO CADASTRO, CHECKOUT STRIPE
    PRIMARY_800: "#D1EFC4", //COR PRINCIPAL DO APP MAIS CLARO - CORES DOS BOTÕES DA PLANS, INPUT LOGIN
    SECONDARY_900: "#8EB87D", //COR SECUNDÁRIA - COR DRAWER CLICADO E DO TEXTO DO DRAWER. COR BOTÃO CLICADO DA RECORRENCIA DO PLANO
    SECONDARY_800: "#D1EFC4", //COR SECUNDÁRIA MAIS CLARA - COR DRAWER CLICADO. COR BOTÃO NÃO CLICADO DA RECORRENCIA DO PLANO
    TERTIARY_900: "#8EB87D", //COR TERCIÁRIA - COR DO ICONE E TEXTO SAIR DO DRAWER
    TERTIARY_800: "#D1EFC4", //COR TERCIÁRIA MAIS CLARA

    GRADIENT_MAIN:[
      'rgba(0,0,0,0.5)',
      'rgba(0,0,0,0.1)',
      'rgba(0,0,0,0.1)',
      '#2e2e2e'
    ]
  },

  FONTFAMILY:{
    BOLD: "Montserrat_700Bold",
    MEDIUM: 'Montserrat_500Medium',
    REGULAR: 'Montserrat_400Regular',
    LIGHT: 'Montserrat_300Light',
    FONTABOUT: "Rajdhani_Medium",
  },

  FONTSIZE:{
    GIANT: RFValue(50, 1080), //USADA 1X NO TÍTULO DA TELA ABOUT
    EXTRABIG: RFValue(24, 1080), //USADA 1X NA TELA DE LOGIN
    BIG: RFValue(20, 1080),
    STANDARD: RFValue(18, 1080),
    MEDIUM: RFValue(16, 1080),
    SMALL: RFValue(14, 1080), 
    EXTRASMALL: RFValue(12, 1080),
  }
};