import { RFPercentage, RFValue } from "react-native-responsive-fontsize";

export default {
  COLORS:{
    ALERT: "#ec1414",

    BACKGROUND_ABOUT: "#f6eadd", //COR PARA A ABOUT, CLICK COURSE, PLANS, EDITPROFILE, LOGIN E CADASTRO
    BACKGROUND_HEADER: "none", //COR DE TODOS OS CABEÇALHOS
    BACKGROUND_FOOTER: "#DCDCDC", //COR DO RODAPÉ
    BACKGROUND_MAIN: "#2e2e2e", //COR PARA A MAIN E CLICKCLASS

    ICON_HEADER: "#759A5B", //COR DO VOLTAR DO HEADER
    ICON_HEADER_OVERPHOTO: "#ffffff", //COR DA PALAVRA LOGIN, ACESSAR APLICATIVO E DRAWER NO HEADER (MAIN E ABOUT)
    ICON_DRAWER: "#1E1E1E", //ÍCONES DENTRO DO DRAWER (TERMOS DE USO E SAIR)

    TITLE_OVERPHOTO_ABOUT: "#ffffff", //USADA PARA O TÍTULO DA ABOUT
    SUBTITLE_OVERPHOTO_ABOUT: "#ffffff", //USADA PARA O SUBTÍTULO DA ABOUT
    TITLE_OVERPHOTO_MAIN: "#ffffff", //USADA PARA O TÍTULO E SUBTÍTULO DA MAIN

    TITLE_ABOUT: '#333033', //USADA PARA PARA OS TAMANHOS EXTRABIG, BIG E STANDARD
    TEXT_ABOUT: '#333033', //USADA PARA PARA OS TAMANHOS MEDIUM, SMALL E EXTRASMALL

    TITLE_MAIN: '#333033', //USADA PARA PARA OS TAMANHOS EXTRABIG, BIG E STANDARD
    TEXT_MAIN: '#333033', //USADA PARA PARA OS TAMANHOS MEDIUM, SMALL E EXTRASMALL

    TEXT_FOOTER: '#1E1E1E', //USADA PARA O TEXTO DO RODAPÉ
    TEXT_BUTTON: "#ffffff", //USADA PARA O TEXTO DOS BOTÕES
 
    PRIMARY_900: "#CC7256", //COR PRINCIPAL DO APP - CORES DOS BOTÕES, LATERAL DO CADASTRO, CHECKOUT STRIPE
    PRIMARY_800: "#E9A593", //COR SECUNDÁRIA - CORES DOS BOTÕES DA PLANS, CLICK DO DRAWER, INPUT LOGIN

    GRADIENT_MAIN:[
      'rgba(0,0,0,0.5)',
      'rgba(0,0,0,0.1)',
      'rgba(0,0,0,0.1)',
      '#2e2e2e'
    ]
  },

  FONTFAMILY:{
    BOLD: "Montserrat_700Bold",
    MEDIUM: 'Montserrat_500Medium',
    REGULAR: 'Montserrat_400Regular',
    LIGHT: 'Montserrat_300Light',
    FONTABOUT: "Rajdhani_Medium",
  },

  FONTSIZE:{
    GIANT: RFValue(50, 1080), //USADA 1X NO TÍTULO DA TELA ABOUT
    EXTRABIG: RFValue(24, 1080), //USADA 1X NA TELA DE LOGIN
    BIG: RFValue(20, 1080),
    STANDARD: RFValue(18, 1080),
    MEDIUM: RFValue(16, 1080),
    SMALL: RFValue(14, 1080), 
    EXTRASMALL: RFValue(12, 1080),
  }
};